[package]
name = "mrktpltsbot"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
description = "Marktplaats search notifications in Telegram (Unofficial)"
edition = "2018"
keywords = ["marktplaats"]
license = "MIT"
publish = true
readme = "README.md"
repository = "https://github.com/eigenein/mrktpltsbot"
version = "0.5.0"

[badges]
is-it-maintained-issue-resolution = { repository = "eigenein/mrktpltsbot" }
is-it-maintained-open-issues = { repository = "eigenein/mrktpltsbot" }

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
debug = "none"
lto = "thin"
strip = true

[lints.clippy]

# Categories:
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

# Individual flags:
future_not_send = "allow"
missing_errors_doc = "allow"
module_name_repetitions = "allow"

[dependencies]
anyhow = "1.0.32"
async-std = { version = "1.6.2", features = ["attributes", "tokio1"] }
backoff = { version = "0.4.0", features = ["async-std"] }
chrono = { version = "0.4.13", features = ["serde"] }
chrono-tz = { version = "0.8.6", features = ["serde"] }
futures = "0.3.5"
lazy_static = "1.4.0"
log = "0.4.11"
redis = { version = "0.24.0", features = ["connection-manager", "async-std-comp"] }
regex = "1.3.9"
reqwest = { version = "0.11.0", features = ["rustls-tls", "gzip", "json"], default-features = false }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
simplelog = "0.12.1"
structopt = "0.3.16"

[dependencies.sentry]
version = "0.32.2"
features = ["backtrace", "contexts", "panic", "transport", "log", "anyhow"]
default-features = false
